export const projects = [
  {
    id: 'draftix',
    name: 'Draftix.tech',
    type: 'Web Application',
    year: '2026',
    status: 'Live',
    category: 'Gaming / Competitive Tools',
    subtitle: 'Competitive tools for Valorant teams and players.',
    description: 'A competitive toolkit for Valorant players and teams. Draftix provides tools for agent and map drafting, tournament bracket creation, and team balancing, all in one place.',
    features: ['Agent Drafting', 'Map Drafting', 'Tournament Bracket Maker', 'Team Balancer'],
    stack: ['React', 'Vite', 'Node.js', 'Supabase', 'Vercel'],
    url: 'https://draftix.tech',
  },
  {
    id: 'tappycard',
    name: 'TappyCard',
    type: 'Web Application / NFC Product',
    year: '2026',
    status: 'Live',
    category: 'Digital Networking / NFC',
    subtitle: 'A reusable NFC digital business card for sharing every connection with one tap.',
    description: 'TappyCard combines a reusable NFC card with a customizable digital profile. A tap or QR scan opens contact details, social profiles, review pages, menus, booking links, and websites directly in the recipient’s browser without requiring an app.',
    features: ['NFC Tap-to-Share', 'QR Code Backup', 'Custom Digital Profiles', 'Contact Detail Sharing', 'Social and Website Links', 'Google Review Links', 'Booking and Menu Links', 'Editable Profile Information'],
    stack: ['React', 'Vite', 'NFC', 'QR Codes'],
    url: 'https://www.tappycard.tech/',
  },
  {
    id: 'seed-track',
    name: 'SEED-TRACK',
    type: 'Web Application',
    year: '2026',
    status: 'In Progress',
    category: 'Seed Inventory / Storage Management',
    subtitle: 'Seed inventory and storage management for the PhilRice Genebank.',
    description: 'A centralized web platform designed to improve seed inventory, storage, request processing, and traceability for the PhilRice Genebank. Ranier leads the project from requirements and planning through implementation, testing, and documentation.',
    features: ['Seed Inventory Management', 'Seed Packet Tracking', 'Barcode and QR Scanning', 'Rack and Tray Monitoring', 'Seed Request Processing', 'Inventory Transaction Tracking', 'Role-Based Access Control', 'Reports and Monitoring', 'AI Seed Assistant'],
    stack: ['React', 'Node.js', 'GraphQL', 'MySQL'],
  },
  {
    id: 'kwenta',
    name: 'Kwenta',
    type: 'Web Application',
    year: '2026',
    status: 'Live',
    category: 'Education / Academic Tools',
    subtitle: 'A mobile-first GWA calculator for Filipino university students.',
    description: 'Kwenta helps Filipino students calculate their GWA using university-specific grading presets, academic-standing estimates, saved semesters, CSV export, and a flexible custom weighted-average calculator.',
    features: ['University-Specific Grade Presets', 'GWA, GPA, and QPI Calculation', 'Academic Standing Estimates', 'Saved Semester History', 'CSV Export', 'Branded Result Sharing', 'Mobile-First Interface', 'Private On-Device Storage'],
    stack: ['Next.js', 'React', 'TypeScript', 'Vitest', 'Vercel'],
    url: 'https://kwenta.ranierteraldico.me/',
  },
]

export const skillGroups = [
  ['FRONTEND', ['React', 'Vite', 'HTML', 'CSS']],
  ['BACKEND', ['Node.js', 'Python']],
  ['DATABASE_AND_SERVICES', ['PostgreSQL', 'Supabase', 'Firebase']],
  ['LANGUAGES', ['Java', 'PHP']],
  ['AI_AGENTS', ['Claude Code', 'Codex', 'Gemini', 'Nano Banana', 'Tripo3D', 'Cline', 'n8n']],
  ['DESIGN', ['Figma', 'Adobe Photoshop']],
  ['DEPLOYMENT', ['Vercel', 'Netlify', 'Render', 'Railway']],
]
