export const projects = [
  {
    id: 'draftix',
    name: 'Draftix.tech',
    type: 'Web Application',
    year: '2026',
    status: 'Live',
    category: 'Gaming / Competitive Tools',
    role: 'Creator / Full-stack Developer',
    subtitle: 'Competitive tools for Valorant teams and players.',
    description: 'A competitive toolkit for Valorant players and teams. Draftix provides tools for agent and map drafting, tournament bracket creation, and team balancing, all in one place.',
    challenge: 'Competitive teams often rely on separate tools or manual processes for agent drafts, map selection, tournament brackets, and balanced team creation.',
    solution: 'Draftix combines the recurring preparation and tournament workflows into one browser-based toolkit designed for players, teams, and organizers.',
    responsibilities: ['Defined the product structure and feature workflows', 'Designed and developed the responsive interface', 'Implemented application state and Supabase-backed services', 'Prepared the application for production deployment'],
    outcome: 'Draftix is live with four focused tools that can be used independently or as part of a team and tournament workflow.',
    features: ['Agent Drafting', 'Map Drafting', 'Tournament Bracket Maker', 'Team Balancer'],
    stack: ['React', 'Vite', 'Node.js', 'Supabase', 'Vercel'],
    url: 'https://draftix.tech',
  },
  {
    id: 'tappycard',
    name: 'TappyCard',
    type: 'Web Application / NFC Product',
    year: '2026',
    status: 'Live',
    category: 'Digital Networking / NFC',
    role: 'Web Developer',
    subtitle: 'A reusable NFC digital business card for sharing every connection with one tap.',
    description: 'TappyCard combines a reusable NFC card with a customizable digital profile. A tap or QR scan opens contact details, social profiles, review pages, menus, booking links, and websites directly in the recipient’s browser without requiring an app.',
    challenge: 'Printed business cards become outdated and require recipients to manually save contact details or search for the correct social and business links.',
    solution: 'The product connects a reusable NFC card to an editable web profile, with QR support as a fallback for devices and situations where NFC is unavailable.',
    responsibilities: ['Developed responsive web experiences for digital profiles', 'Supported tap, scan, and link-sharing workflows', 'Organized contact, social, review, booking, and website destinations', 'Tested the experience across mobile browsing scenarios'],
    outcome: 'TappyCard is live as a reusable contact-sharing product that works through the recipient’s browser without requiring a dedicated application.',
    features: ['NFC Tap-to-Share', 'QR Code Backup', 'Custom Digital Profiles', 'Contact Detail Sharing', 'Social and Website Links', 'Google Review Links', 'Booking and Menu Links', 'Editable Profile Information'],
    stack: ['React', 'Vite', 'NFC', 'QR Codes'],
    url: 'https://www.tappycard.tech/',
  },
  {
    id: 'seed-track',
    name: 'SEED-TRACK',
    type: 'Web Application',
    year: '2026',
    status: 'In Progress',
    category: 'Seed Inventory / Storage Management',
    role: 'Project Lead / Software Engineer',
    subtitle: 'Seed inventory and storage management for the PhilRice Genebank.',
    description: 'A centralized web platform designed to improve seed inventory, storage, request processing, and traceability for the PhilRice Genebank. Ranier leads the project from requirements and planning through implementation, testing, and documentation.',
    challenge: 'Important seed inventory, storage, request, and traceability activities depend on manual or separated workflows that make records harder to coordinate and monitor.',
    solution: 'SEED-TRACK centralizes seed records, packet movement, storage locations, requests, transactions, reports, and role-based access in one web platform.',
    responsibilities: ['Coordinate the development team and client communication', 'Gather and refine system requirements', 'Manage the product backlog and sprint priorities', 'Review system features, workflows, architecture, and database requirements', 'Coordinate testing and technical documentation', 'Keep implementation aligned with PhilRice Genebank requirements'],
    outcome: 'The system is in active development, with implementation, testing, documentation, and workflow refinement continuing with client feedback.',
    features: ['Seed Inventory Management', 'Seed Packet Tracking', 'Barcode and QR Scanning', 'Rack and Tray Monitoring', 'Seed Request Processing', 'Inventory Transaction Tracking', 'Role-Based Access Control', 'Reports and Monitoring', 'AI Seed Assistant'],
    stack: ['React', 'Node.js', 'GraphQL', 'MySQL'],
  },
  {
    id: 'kwenta',
    name: 'Kwenta',
    type: 'Web Application',
    year: '2026',
    status: 'Live',
    category: 'Education / Academic Tools',
    role: 'Creator / Full-stack Developer',
    subtitle: 'A mobile-first GWA calculator for Filipino university students.',
    description: 'Kwenta helps Filipino students calculate their GWA using university-specific grading presets, academic-standing estimates, saved semesters, CSV export, and a flexible custom weighted-average calculator.',
    challenge: 'Philippine universities use different grading scales, terminology, rounding rules, and academic-standing classifications, making generic GPA calculators unreliable for many students.',
    solution: 'Kwenta provides separate university presets with documented grading behavior while retaining a custom weighted-average calculator for students whose institution is not yet supported.',
    responsibilities: ['Researched university grading rules and source material', 'Implemented weighted calculation and academic-standing logic', 'Built the responsive university selection and calculator interfaces', 'Added local persistence, result sharing, and CSV export', 'Set up testing, technical SEO, and deployment'],
    outcome: 'Kwenta is live as a mobile-first academic tool with university-specific calculators, private on-device storage, and shareable results.',
    features: ['University-Specific Grade Presets', 'GWA, GPA, and QPI Calculation', 'Academic Standing Estimates', 'Saved Semester History', 'CSV Export', 'Branded Result Sharing', 'Mobile-First Interface', 'Private On-Device Storage'],
    stack: ['Next.js', 'React', 'TypeScript', 'Vitest', 'Vercel'],
    url: 'https://kwenta.ranierteraldico.me/',
  },
  {
    id: 'resuma',
    name: 'Resuma',
    type: 'Web Application',
    year: '2026',
    status: 'Live',
    category: 'Productivity / Career Tools',
    role: 'Creator / Frontend Developer',
    subtitle: 'A focused resume builder with real-time document preview and direct export.',
    description: 'Resuma is a privacy-friendly resume builder that lets users edit structured resume sections while seeing the finished document update in real time. It supports flexible formatting, reorderable entries, local draft storage, and direct PDF and DOCX export.',
    challenge: 'Traditional resume editing separates form entry from the final document, making formatting problems difficult to notice until export or printing.',
    solution: 'Resuma places a structured editor beside a continuously updated resume preview, giving users immediate feedback while they write and reorder content.',
    responsibilities: ['Designed the editor and document-preview architecture', 'Implemented real-time synchronization between fields and output', 'Built reorderable education, experience, and project entries', 'Added local draft persistence and document export', 'Optimized the builder for desktop and mobile workflows'],
    outcome: 'Resuma is live as a no-account resume workspace with local drafts, multiple formats, adjustable typography, and direct document export.',
    features: ['Real-Time Resume Preview', 'PDF and DOCX Export', 'Multiple Resume Formats', 'Adjustable Typography and Title Colors', 'Drag-and-Drop Entry Reordering', 'Local Draft Storage', 'Responsive Builder Interface', 'No Account Required'],
    stack: ['Next.js', 'React', 'TypeScript', 'GSAP', 'jsPDF', 'DOCX', 'Vercel'],
    url: 'https://resuma.ranierteraldico.me/',
  },
]

export const skillGroups = [
  ['FRONTEND', ['React', 'Vite', 'HTML', 'CSS']],
  ['BACKEND', ['Node.js', 'Python']],
  ['DATABASE_AND_SERVICES', ['PostgreSQL', 'Supabase', 'Firebase']],
  ['LANGUAGES', ['Java', 'PHP']],
  ['AI_AGENTS', ['Claude Code', 'Codex', 'Gemini', 'Nano Banana', 'Tripo3D', 'Cline', 'n8n']],
  ['SEO_AND_DISCOVERY', ['Technical SEO', 'On-Page SEO', 'Structured Data', 'Google Search Console', 'Personal Brand SEO', 'Business Website SEO']],
  ['DESIGN', ['Figma', 'Adobe Photoshop']],
  ['DEPLOYMENT', ['Vercel', 'Netlify', 'Render', 'Railway']],
]
